# Generated by Django 4.1.7 on 2023-03-07 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='models',
            new_name='Notes',
        ),
    ]
