# Generated by Django 4.2 on 2023-04-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_notes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='email',
            field=models.EmailField(default='asa@dsd.cs', max_length=254),
        ),
        migrations.AddField(
            model_name='notes',
            name='fullname',
            field=models.CharField(default='hello', max_length=50),
        ),
        migrations.AddField(
            model_name='notes',
            name='password',
            field=models.CharField(default='hello', max_length=50),
        ),
    ]
