# Generated by Django 4.2 on 2023-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_notes_body_remove_notes_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='notes',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
