# Generated by Django 4.2 on 2023-04-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notes_email_alter_notes_fullname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='user_data',
        ),
    ]
